# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  iphonemax_cart_service:
    image: iphonemax_cart_service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5005:5005
